const GET_USERS_SAGA = 'GET_USERS_SAGA'
const SET_USERS = 'SET_USERS'
const GET_POSTS_SAGA = 'GET_POSTS_SAGA'
const SET_POSTS = 'SET_POSTS'
const FILTER_USERS = 'FILTER_USERS'
const FILTERING_USERS = 'FILTERING_USERS'

export {
  GET_USERS_SAGA,
  GET_POSTS_SAGA,
  SET_POSTS,
  SET_USERS,
  FILTER_USERS,
  FILTERING_USERS,
}
